# Generated by Django 4.0.4 on 2022-06-03 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaje',
            name='fecha_regreso',
            field=models.DateField(blank=True, null=True),
        ),
    ]
